import uuid
import yaml
import structlog
from pathlib import Path
from datetime import datetime
from .config import settings
from .db import get_db_pool, audit
from .github_manager import GitHubManager
from .models import Product

log = structlog.get_logger()

class ProductFactory:
    def __init__(self):
        self.github = GitHubManager()
        self.catalog = self._load_catalog()

    def _load_catalog(self) -> dict:
        path = Path(settings.product_catalog_path)
        if not path.exists():
            # Fallback embedded catalog for breakthrough zero-config start
            return {
                "templates": {
                    "mesh_messenger": {
                        "name": "Mesh Messenger",
                        "description": "Decentralized encrypted messaging with monetizable channels",
                        "target_mrr_default": 8000,
                        "scaffold": {
                            "README.md": "# Mesh Messenger\nAutonomous product generated by Apex Zero-Human Grid.\n",
                            "src/main.py": "print('Mesh Messenger live')\n",
                            "pricing.yaml": "plans:\n  - name: pro\n    price: 29\n    interval: month\n"
                        }
                    },
                    "data_monetization_api": {
                        "name": "Data Monetization API",
                        "description": "Privacy-preserving data marketplace + API",
                        "target_mrr_default": 15000,
                        "scaffold": {
                            "README.md": "# Data Monetization API\nGenerated by Zero-Human Grid.\n",
                            "api/main.py": "from fastapi import FastAPI\napp = FastAPI()\n@app.get('/health')\ndef health(): return {'status':'ok'}\n",
                            "pricing.yaml": "plans:\n  - name: enterprise\n    price: 499\n    interval: month\n"
                        }
                    },
                    "governance_platform": {
                        "name": "Governance Platform",
                        "description": "Policy + compliance automation for regulated industries",
                        "target_mrr_default": 12000,
                        "scaffold": {
                            "README.md": "# Governance Platform\nZero-Human generated.\n",
                            "core/policy.py": "# Policy engine stub\n",
                            "pricing.yaml": "plans:\n  - name: compliance\n    price: 199\n    interval: month\n"
                        }
                    },
                    "trading_bot": {
                        "name": "Autonomous Trading Bot",
                        "description": "Risk-gated algorithmic trading with human capital approval",
                        "target_mrr_default": 25000,
                        "scaffold": {
                            "README.md": "# Trading Bot\nCapital actions require multi-gate approval.\n",
                            "bot/strategy.py": "# Strategy with confidence gates\n",
                            "pricing.yaml": "plans:\n  - name: alpha\n    price: 999\n    interval: month\n"
                        }
                    }
                }
            }
        with open(path) as f:
            return yaml.safe_load(f)

    async def create(self, template_id: str, name: str, target_mrr: float, metadata: dict = None) -> dict:
        if template_id not in self.catalog.get("templates", {}):
            raise ValueError(f"Unknown template: {template_id}. Available: {list(self.catalog.get('templates', {}).keys())}")

        template = self.catalog["templates"][template_id]
        product_id = str(uuid.uuid4())

        pool = await get_db_pool()
        async with pool.acquire() as conn:
            row = await conn.fetchrow(
                """
                INSERT INTO products (id, name, template_id, status, target_mrr, metadata)
                VALUES ($1, $2, $3, 'private', $4, $5)
                RETURNING id, name, template_id, status, target_mrr, created_at
                """,
                product_id, name, template_id, target_mrr, metadata or {}
            )

        await audit(
            "product_created",
            resource_id=product_id,
            payload={"template_id": template_id, "name": name, "target_mrr": target_mrr, "status": "private"},
            confidence=0.95
        )

        log.info("product_created_private", id=product_id, name=name, template=template_id)
        return dict(row)

    async def scaffold_github(self, product_id: str):
        pool = await get_db_pool()
        async with pool.acquire() as conn:
            product = await conn.fetchrow("SELECT * FROM products WHERE id = $1", product_id)
            if not product:
                return

            template = self.catalog["templates"][product["template_id"]]
            repo_name = f"apex-{product['name'].lower().replace(' ', '-')}-{product_id[:8]}"
            
            try:
                repo_info = await self.github.create_repo(
                    name=repo_name,
                    description=template.get("description", ""),
                    private=True
                )
                await self.github.push_scaffold(repo_info["full_name"], template.get("scaffold", {}))
                
                await conn.execute(
                    "UPDATE products SET github_repo = $1, updated_at = NOW() WHERE id = $2",
                    repo_info["full_name"], product_id
                )
                await audit("product_scaffolded", resource_id=product_id, payload=repo_info)
            except Exception as e:
                log.error("scaffold_failed", product_id=product_id, error=str(e))
                await audit("scaffold_failed", resource_id=product_id, payload={"error": str(e)}, confidence=0.1)

    async def make_public(self, product_id: str) -> dict:
        """Only callable after human approval."""
        pool = await get_db_pool()
        async with pool.acquire() as conn:
            product = await conn.fetchrow("SELECT * FROM products WHERE id = $1", product_id)
            if not product:
                raise ValueError("Product not found")
            if product["status"] == "public":
                return {"status": "already_public"}

            # In real system: create Stripe product + prices here
            # For now mark public and log
            await conn.execute(
                "UPDATE products SET status = 'public', updated_at = NOW() WHERE id = $1",
                product_id
            )
            await audit(
                "product_made_public",
                resource_id=product_id,
                actor="governor",
                payload={"previous_status": product["status"]},
                confidence=1.0
            )
            log.info("product_public", id=product_id)
            return {"status": "public", "product_id": product_id}

    async def list_all(self) -> list:
        pool = await get_db_pool()
        async with pool.acquire() as conn:
            rows = await conn.fetch("SELECT * FROM products ORDER BY created_at DESC")
            return [dict(r) for r in rows]
